# Generated by Django 2.1.3 on 2018-11-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alutracer.PersonalInformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_graduated',
            field=models.DateTimeField(),
        ),
    ]
