# Generated by Django 2.1.3 on 2018-11-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0003_auto_20181121_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='address_organization_or_employer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='organization_or_employer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
