# Generated by Django 2.1.3 on 2018-12-07 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alutracer', '0007_auto_20181207_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallax_1', models.ImageField(upload_to='media')),
                ('parallax_1_heading_content', models.CharField(max_length=255)),
                ('parallax_1_content', models.TextField()),
                ('parallax_2', models.ImageField(upload_to='media')),
                ('parallax_2_heading_content', models.CharField(max_length=255)),
                ('parallax_2_content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_description',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_heading',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_1',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_1_content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_1_heading_content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_2_content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='parallax_2_heading_content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='thumbnail',
        ),
    ]
