# Generated by Django 2.1.3 on 2018-12-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0008_auto_20181207_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parallax',
            old_name='parallax_1_heading_content',
            new_name='parallax_1_heading',
        ),
        migrations.RenameField(
            model_name='parallax',
            old_name='parallax_2_heading_content',
            new_name='parallax_2_heading',
        ),
    ]
