# Generated by Django 2.1.3 on 2018-12-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0010_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='address_organization_or_employer',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='date_graduated',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='organization_or_employer',
        ),
    ]
