# Generated by Django 2.1.3 on 2018-12-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0011_auto_20181211_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
