# Generated by Django 2.1.3 on 2018-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0013_auto_20181212_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
