# Generated by Django 2.1.3 on 2018-12-20 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0014_auto_20181212_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='address_organization_or_employer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alutracer.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_graduated',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='organization_or_employer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
