# Generated by Django 2.1.3 on 2018-12-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0015_auto_20181220_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='type_of_organization',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('NGO', 'NGO'), ('Non-Profit', 'Non-Profit')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
