# Generated by Django 2.1.3 on 2018-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0016_personalinformation_type_of_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='related_job',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='type_of_organization',
            field=models.CharField(max_length=20),
        ),
    ]
