# Generated by Django 2.1.3 on 2018-12-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0017_auto_20181220_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='related_job',
        ),
    ]
