# Generated by Django 2.1.3 on 2018-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0018_remove_personalinformation_related_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='related_job',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
