# Generated by Django 2.1.3 on 2018-12-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0019_personalinformation_related_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='finish_graduate_degree',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='number_year_company',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='place_of_work',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
