# Generated by Django 2.1.3 on 2018-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0020_auto_20181220_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='department_division',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='designation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_status',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='month_range_income',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='reason_staying_job',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
