# Generated by Django 2.1.3 on 2018-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0021_auto_20181220_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='month_range_income',
            new_name='monthly_range_income',
        ),
    ]
