# Generated by Django 2.1.3 on 2018-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0023_auto_20181220_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='advertisement_media',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='case_of_unemployed',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='monthly_income',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='nature_of_employment',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='not_persuing_futher_studies',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='number_of_years',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='obtaining_degree_ndmc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='persuing_degree_ndmc',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='persuing_futher_studies',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
