# Generated by Django 2.1.3 on 2019-02-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0024_auto_20181220_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='address',
            new_name='a_address_line_2',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='address_organization_or_employer',
            new_name='a_city',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='department_division',
            new_name='a_country',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='advertisement_media',
            new_name='a_state_province_region',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='case_of_unemployed',
            new_name='a_street_adress',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='designation',
            new_name='a_zip_code',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='country',
            new_name='b_address_line_2',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='monthly_income',
            new_name='b_city',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='monthly_range_income',
            new_name='b_country',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='not_persuing_futher_studies',
            new_name='b_state_province_region',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='obtaining_degree_ndmc',
            new_name='b_street_adress',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='organization_or_employer',
            new_name='b_zip_code',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='finish_graduate_degree',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='nature_of_employment',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='number_of_years',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='number_year_company',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='persuing_degree_ndmc',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='persuing_futher_studies',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='place_of_work',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='reason_staying_job',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='related_job',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_media_account',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='type_of_organization',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], max_length=10),
        ),
    ]
