# Generated by Django 2.1.3 on 2019-02-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0025_auto_20190203_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='a_state_province_region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='b_state_province_region',
            field=models.CharField(max_length=255),
        ),
    ]
