# Generated by Django 2.1.3 on 2019-02-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0026_auto_20190203_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='date_graduated',
        ),
    ]
