# Generated by Django 2.1.3 on 2019-02-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0028_auto_20190204_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='twitter_account',
        ),
    ]
