# Generated by Django 2.1.3 on 2019-02-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0030_auto_20190204_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alutracer.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_graduated',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
