# Generated by Django 2.1.3 on 2019-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0031_auto_20190204_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='address_organization_or_employer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='organization_or_employer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='type_of_organization',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
