# Generated by Django 2.1.3 on 2019-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0032_auto_20190204_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='department_division',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='designation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='employment_type',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='finish_graduate_degree',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_status',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='monthly_range_income',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='number_year_company',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='obtaining_degree_ndmc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='occupational_classification',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='persuing_degree_ndmc',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='place_of_work',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='reason_staying_job',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='related_job',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
