# Generated by Django 2.1.3 on 2019-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0033_auto_20190204_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='current_job',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
