# Generated by Django 2.1.3 on 2019-02-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0034_personalinformation_current_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='first_employment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='monthly_income_range',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='nature_of_employment',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='number_of_years',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='reason_of_unemployed',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='work_related_course',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
