# Generated by Django 2.1.3 on 2019-02-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0035_auto_20190204_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='academic_professional',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='class_size',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='communication_skills',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='critical_thinking_skills',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='degree_program',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='extracurricular_activities',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='information_technology_skills',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='interdisciplinary_learning',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='international_Community',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='laboratory_resources',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='learning_efficiency',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='library_resources',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='local_community',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='meeting_present',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='not_pursuing_further_studies',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='opportunities_dbroad',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='people_skills',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='personality_development',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='premium_given_research',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='problem_solving_skills',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='professors_knowledge',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='professors_pedagogical',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='pursuing_further_studies',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='quality_instruction',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='range_of_courses',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='relevance_profession',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='research_capability',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='salary_improvement',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='teacher_student_relationships',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='teaching_Learning',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='values_formation',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
