# Generated by Django 2.1.3 on 2019-02-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0036_auto_20190205_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='international_Community',
            new_name='international_community',
        ),
    ]
