# Generated by Django 2.1.3 on 2019-02-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0037_auto_20190205_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='opportunities_dbroad',
            new_name='opportunities_abroad',
        ),
    ]
