# Generated by Django 2.1.3 on 2019-02-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0039_auto_20190205_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='degree_program',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='not_pursuing_further_studies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='pursuing_further_studies',
            field=models.CharField(max_length=255),
        ),
    ]
