# Generated by Django 2.1.3 on 2019-02-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alutracer', '0043_auto_20190205_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='contact_4',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_5',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='email_id_4',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='email_id_5',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='name_4',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='name_5',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='social_network_id_4',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='social_network_id_5',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
