from django import forms
from django.contrib.auth import get_user_model
from .models import Course, Index, Thumbnail, Parallax, PersonalInformation

User = get_user_model()

class PersonalInformationForm(forms.ModelForm):
    class Meta:
        model = PersonalInformation
        fields = [
            'last_name',
            'first_name',
            'middle_name',
            'gender',
            'date_of_birth',
            'civil_status',
            'email',
            'mobile_number',
            'a_street_adress',                     
            'a_address_line_2',                    
            'a_city',                              
            'a_state_province_region',
            'a_zip_code',                          
            'a_country',
            'b_street_adress',                     
            'b_address_line_2',                    
            'b_city',                              
            'b_state_province_region',
            'b_zip_code',                          
            'b_country',
            'facebook_account',
            'twitter_account',
            'course',
            'date_graduated',
            'organization_or_employer',
            'address_organization_or_employer',
            'type_of_organization',
            'employment_type',
            'occupational_classification',
            'related_job',
            'number_year_company',
            'place_of_work',
            'finish_graduate_degree',
            'reason_staying_job',
            'designation',
            'department_division',
            'job_status',
            'monthly_range_income',
            'persuing_degree_ndmc',
            'obtaining_degree_ndmc',
            'current_job',
            'first_employment',
            'work_related_course',
            'nature_of_employment',
            'number_of_years',
            'monthly_income_range',               
            'reason_of_unemployed',
            'academic_professional',
            'research_capability',
            'learning_efficiency',
            'communication_skills',
            'people_skills',
            'problem_solving_skills',
            'information_technology_skills',
            'meeting_present',
            'local_community',
            'international_community',
            'critical_thinking_skills',
            'salary_improvement',
            'opportunities_abroad',
            'personality_development',
            'values_formation',
            'range_of_courses',
            'relevance_profession',
            'extracurricular_activities',
            'premium_given_research',
            'interdisciplinary_learning',
            'teaching_learning',
            'quality_instruction',
            'teacher_student_relationships',
            'library_resources',
            'laboratory_resources',
            'class_size',
            'professors_pedagogical',
            'professors_knowledge',
            'degree_program',
            'pursuing_further_studies',     
            'not_pursuing_further_studies',
            'name_1',
            'contact_1',                        
            'email_id_1',                        
            'social_network_id_1',  

            'name_2',
            'contact_2',                        
            'email_id_2',                        
            'social_network_id_2',    

            'name_3',
            'contact_3',                        
            'email_id_3',                        
            'social_network_id_3', 

            'name_4',
            'contact_4',                        
            'email_id_4',                        
            'social_network_id_4',

            'name_5',
            'contact_5',                        
            'email_id_5',                        
            'social_network_id_5',


        ]