# Generated by Django 2.1.3 on 2018-11-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_modified',
        ),
    ]
