# Generated by Django 2.1.3 on 2018-11-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0002_auto_20181119_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
