# Generated by Django 2.1.3 on 2018-11-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0003_auto_20181121_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Year',
            new_name='year',
        ),
    ]
