# Generated by Django 2.1.3 on 2018-12-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0004_auto_20181121_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='firtsname',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(null=True, upload_to='cover'),
        ),
    ]
