# Generated by Django 2.1.3 on 2018-12-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0005_auto_20181203_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
