# Generated by Django 2.1.3 on 2018-12-06 07:25

from django.db import migrations, models
import pdfdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0006_auto_20181203_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='pdf', validators=[pdfdrive.models.PathAndRename]),
        ),
    ]
