# Generated by Django 2.1.3 on 2019-01-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0007_auto_20181206_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Year',
            field=models.CharField(blank=True, choices=[('1st', 'Firs Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4rt', 'Fourth Year')], default=True, max_length=6),
        ),
    ]
