# Generated by Django 2.1.3 on 2019-01-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdrive', '0008_auto_20190113_2339'),
        ('pdfdrive', '0008_auto_20181220_1343'),
    ]

    operations = [
    ]
